# Generated by Django 3.2.6 on 2021-08-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_feedback', models.TextField()),
                ('mood_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
