# Generated by Django 3.2.6 on 2021-08-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='mood_level',
            field=models.IntegerField(default=0),
        ),
    ]
